# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t2a.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tt2a.proto\x12\x03t2a\"&\n\x12TextToAudioRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"+\n\x13TextToAudioResponse\x12\x14\n\x0c\x61udioFileUrl\x18\x01 \x01(\t2]\n\x12TextToAudioService\x12G\n\x12\x43onvertTextToAudio\x12\x17.t2a.TextToAudioRequest\x1a\x18.t2a.TextToAudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 't2a_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTTOAUDIOREQUEST']._serialized_start=18
  _globals['_TEXTTOAUDIOREQUEST']._serialized_end=56
  _globals['_TEXTTOAUDIORESPONSE']._serialized_start=58
  _globals['_TEXTTOAUDIORESPONSE']._serialized_end=101
  _globals['_TEXTTOAUDIOSERVICE']._serialized_start=103
  _globals['_TEXTTOAUDIOSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
