# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import t2a_pb2 as t2a__pb2


class TextToAudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertTextToAudio = channel.unary_unary(
                '/t2a.TextToAudioService/ConvertTextToAudio',
                request_serializer=t2a__pb2.TextToAudioRequest.SerializeToString,
                response_deserializer=t2a__pb2.TextToAudioResponse.FromString,
                )


class TextToAudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertTextToAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToAudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertTextToAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertTextToAudio,
                    request_deserializer=t2a__pb2.TextToAudioRequest.FromString,
                    response_serializer=t2a__pb2.TextToAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            't2a.TextToAudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextToAudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertTextToAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/t2a.TextToAudioService/ConvertTextToAudio',
            t2a__pb2.TextToAudioRequest.SerializeToString,
            t2a__pb2.TextToAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
